[versions]
androidGradlePlugin = "7.3.1"
#androidGradlePlugin = "4.2.2"
kotlin = "1.6.0"

[libraries]
android-gradlePlugin-api = { group = "com.android.tools.build", name = "gradle-api", version.ref = "androidGradlePlugin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }